name: Publish on NPM
on:
  schedule:
    - cron: "0 10 * * *"
  push:
jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      is_new_version: ${{steps.git-check.outputs.modified}}
      new_version: ${{steps.save-version.outputs.ver-number}}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/devicons/devicon/releases/latest | \
          jq -r ".tag_name" > release-versions/swagger-ui-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Save new version number
        id: save-version
        run: cat ::set-output name=ver-number::release-versions/swagger-ui-latest.txt
  release:
    needs: check_version
    if: needs.jobs.outputs.is_new_version == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish --non-interactive --new-version ${{needs.jobs.outputs.new_version}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
