name: Publish on NPM
on:
  schedule:
    - cron: "0 10 * * *"
  push:
env:
  NPM_TOKEN: NPM_TOKEN
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
      - name: Run publish script
        run: yarn release
